[camera]
preview_width = 640
preview_height = 480
still_width = 4056
still_height = 3040
buffer_count_preview = 4
buffer_count_still = 1
async_save_queue_size = 2
fps = 10
save_root = /home/pi/data/images_and_labels
capture_cooldown_sec = 0.05
capture_strategy = switch_burst
burst_count = 2

[exposure]
ae_enable = true
ae_exposure_mode = short

; only used if ae_enable = false
exposure_time_us =
analogue_gain =

[model]
model_path = /home/pi/beecam/camera/packerout/model_v1/network.rpk
labels_path = /home/pi/beecam/camera/packerout/model_v1/labels.txt
threshold = 0.25
iou = 0.15
max_detections = 10
bbox_order = xy
bbox_normalization = true
ignore_dash_labels = true
preserve_aspect_ratio = false
postprocess =

[stale_detection]
enabled = true
detection_sec = 7.0
iou_threshold = 0.3
center_threshold = 0.1
expire_sec = 5
area_ratio_min = 0.50
area_ratio_max = 2.00

[timelapse]
enabled = False
interval_sec = 1

[storage]
check_path = /home/pi/data
stop_percent = 97
check_interval_sec = 60

[schedule]
schedule_wpi_path = /home/pi/wittypi/schedule.wpi

[oled]
enabled = true
refresh_sec = 1.0

[debug]
log_stale_detections = false
stale_log_interval_sec = 5.0
fps_log_interval_sec = 0.0
log_capture_queue = false
log_startup = false


[service]
restart_on_exception = true
restart_delay_sec = 2.0


[logging]
exception_log_path = /home/pi/data/logs/beecam_exception_log.csv
